#!/bin/sh -x


MAKE="gmake -B -j8"
#ARCH=cpuomp1
ARCH=cpuomp20
#ARCH=mic

${MAKE} MAKEMACRO="-DIS_NO_BRANCH=1 -DCALC_PRT=1 -DCALC_KDE=1 -DCALC_MCS=1 -DCALC_DST=1" EXE=${ARCH}_nobranch_full
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=1 -DCALC_PRT=0 -DCALC_KDE=0 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_nobranch_none
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=1 -DCALC_PRT=1 -DCALC_KDE=0 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_nobranch_prt
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=1 -DCALC_PRT=0 -DCALC_KDE=1 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_nobranch_kde
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=1 -DCALC_PRT=0 -DCALC_KDE=0 -DCALC_MCS=1 -DCALC_DST=0" EXE=${ARCH}_nobranch_mcs

${MAKE} MAKEMACRO="-DIS_NO_BRANCH=0 -DCALC_PRT=1 -DCALC_KDE=1 -DCALC_MCS=1 -DCALC_DST=1" EXE=${ARCH}_branch_full
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=0 -DCALC_PRT=0 -DCALC_KDE=0 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_branch_none
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=0 -DCALC_PRT=1 -DCALC_KDE=0 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_branch_prt
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=0 -DCALC_PRT=0 -DCALC_KDE=1 -DCALC_MCS=0 -DCALC_DST=0" EXE=${ARCH}_branch_kde
${MAKE} MAKEMACRO="-DIS_NO_BRANCH=0 -DCALC_PRT=0 -DCALC_KDE=0 -DCALC_MCS=1 -DCALC_DST=0" EXE=${ARCH}_branch_mcs




