
include ../GNUmakefile.common.mk


OBJ += ../frontend/rmsd.o
OBJ += ../frontend/load.o
OBJ += ../frontend/data.o
OBJ += ../frontend/frontend.o
OBJ += ../frontend/util_optimize_soa_cpu.o
OBJ += ../frontend/util_optimize_soa_gpu.o
OBJ += ../frontend/util_optimize_soa_mic.o
default: $(OBJ)


include ../GNUmakefile.common.rules

